name: Lets_Chat CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      # Frontend Setup
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
      
      # Backend Setup
      - name: Install backend dependencies
        run: npm install
        working-directory: backend
      # Add any backend tests here if you have them
  
  deploy_to_staging:
    needs: build_and_test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku Staging
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"

  deploy_to_production:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku Production
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PRODUCTION_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"
