name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install and Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Copy Frontend Build to Backend
      run: |
        rm -rf backend/public
        mv frontend/dist backend/public

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "backend"